version: '3.6'
services:
  notes:
    build:
      context: ../..
      dockerfile: "./.infra/development-environment/dev.Dockerfile"
    image: notes
    ports:
      - "8081:8081"
    volumes:
      - ../../:/usr/src/app:delegated
      - /usr/src/app/node_modules
    networks:
      - notes
networks:
  notes:
    driver: bridge
